# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MStoreClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MStoreClone
pod 'Alamofire', '~> 5.2'
pod 'SDWebImage', '~> 5.0'
pod 'JGProgressHUD'

  target 'MStoreCloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MStoreCloneUITests' do
    # Pods for testing
  end

end
